services:
  jupyter:
    container_name: clinical-notebook
    build:
      context: .
      dockerfile: scripts/Dockerfile-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
    restart: unless-stopped
    environment:
      - JUPYTER_ENABLE_LAB=yes


