# ==============================================================================
# CDISC SDTM Findings Domain Code Generator
# ==============================================================================
#
# File: emit_findings_oak_from_spec.R
# Purpose: Dynamically generate R code for mapping CDASH raw data to SDTM
#          Findings domains using sdtm.oak package
#
# Input:
#   - CDISC Collection Specializations Excel file
#   - Raw CDASH CSV data file
#   - Study controlled terminology CSV file
#
# Output:
#   - R script for SDTM Findings domain mapping
#   - Generated SDTM dataset CSV file
#
# Author: Auto-generated by CDISC 360I SDTM Oak Code Generator
# Version: 1.0
# Date: $(date)
#
# Dependencies: sdtm.oak, dplyr, readxl
# ==============================================================================

# Load required packages with error handling
tryCatch({
  if (!requireNamespace("readxl", quietly = TRUE)) {
    stop("Required package 'readxl' is not installed. Please run: install.packages('readxl')")
  }
  if (!requireNamespace("dplyr", quietly = TRUE)) {
    stop("Required package 'dplyr' is not installed. Please run: install.packages('dplyr')")
  }
}, error = function(e) {
  cat("ERROR: Package dependency check failed\n")
  cat("Details:", e$message, "\n")
  stop(e)
})

#' Generate SDTM Findings Domain Mapping Code
#'
#' @description
#' Dynamically generates R code for mapping CDASH raw data to SDTM Findings domains
#' using the sdtm.oak package. The function reads CDISC Collection Specializations,
#' raw data structure, and controlled terminology to produce optimized mapping code.
#'
#' @param spec_path Character. Path to CDISC Collection Specializations Excel file
#' @param raw_csv_path Character. Path to raw CDASH CSV data file
#' @param ct_csv_path Character. Path to study controlled terminology CSV file
#' @param domain Character. Target SDTM domain code (default: "VS")
#' @param out_r_path Character. Output path for generated R script (optional)
#'
#' @return Character vector containing the generated R code lines
#'
#' @examples
#' \dontrun{
#' # Generate VS domain mapping code
#' code_lines <- emit_findings_oak_from_spec(
#'   spec_path = "cdisc_collection_dataset_specializations_draft.xlsx",
#'   raw_csv_path = "cdash/VS.csv",
#'   ct_csv_path = "study_ct.csv",
#'   domain = "VS",
#'   out_r_path = "generated_vs_mapping.R"
#' )
#' }
#'
#' @export
emit_findings_oak_from_spec <- function(spec_path, raw_csv_path, ct_csv_path, domain = "VS", out_r_path = NULL) {
  
  # Input validation and logging
  cat("=== CDISC SDTM Findings Code Generator ===\n")
  cat("Starting code generation for domain:", domain, "\n")
  cat("Timestamp:", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n\n")
  
  # Validate input parameters
  if (!is.character(spec_path) || length(spec_path) != 1) {
    stop("ERROR: spec_path must be a single character string")
  }
  if (!is.character(raw_csv_path) || length(raw_csv_path) != 1) {
    stop("ERROR: raw_csv_path must be a single character string")
  }
  if (!is.character(ct_csv_path) || length(ct_csv_path) != 1) {
    stop("ERROR: ct_csv_path must be a single character string")
  }
  if (!is.character(domain) || length(domain) != 1) {
    stop("ERROR: domain must be a single character string")
  }
  
  # Validate file existence
  if (!file.exists(spec_path)) {
    stop("ERROR: Specification file not found: ", spec_path)
  }
  if (!file.exists(raw_csv_path)) {
    stop("ERROR: Raw data file not found: ", raw_csv_path)
  }
  if (!file.exists(ct_csv_path)) {
    stop("ERROR: Controlled terminology file not found: ", ct_csv_path)
  }
  
  cat("✓ Input validation passed\n")
  
  # Read and validate input files
  tryCatch({
    cat("Reading specification file...\n")
    spec <- readxl::read_excel(spec_path, sheet = "Collection Specializations")
    
    cat("Reading raw data file...\n")
    raw <- utils::read.csv(raw_csv_path, stringsAsFactors = FALSE)
    
    cat("Reading controlled terminology file...\n")
    ct_test <- utils::read.csv(ct_csv_path, stringsAsFactors = FALSE)
    
  }, error = function(e) {
    stop("ERROR: Failed to read input files - ", e$message)
  })
  
  # Domain-specific processing
  dom <- toupper(domain)
  dom_spec <- subset(spec, toupper(domain) == dom)
  raw_cols <- names(raw)
  
  cat("✓ Successfully loaded input files\n")
  cat("Domain:", dom, "\n")
  cat("Raw data columns:", length(raw_cols), "\n")
  cat("Domain specification rows:", nrow(dom_spec), "\n\n")
  
  # Detect parameter groups (anything with _<DOM>ORRES pattern)
  orres_pattern <- paste0("_", dom, "ORRES$")
  orres_vars <- grep(orres_pattern, raw_cols, value = TRUE)
  groups <- unique(sub("_.*$", "", orres_vars))
  
  # Validate detected groups
  if (length(groups) == 0) {
    warning("No parameter groups detected for domain ", dom,
            ". Expected variables matching pattern '*_", dom, "ORRES'")
    cat("⚠ WARNING: No parameter groups found\n")
  } else {
    cat("✓ Detected", length(groups), "parameter groups:", paste(groups, collapse = ", "), "\n")
  }
  
  # Helper Functions ----
  
  #' Extract test information from specification for a parameter group
  #' @param group Character. Parameter group name (e.g., "WEIGHT", "HEIGHT")
  #' @return List with testcd and test name
  test_info <- function(group) {
    tryCatch({
      # Look up group in domain specification
      df <- dom_spec[toupper(dom_spec$vlm_group_id) == toupper(group) |
                       startsWith(toupper(dom_spec$collection_group_id), toupper(group)), , drop = FALSE]
      
      # Extract TESTCD and TEST name from specification
      testcd <- if (nrow(df) && any(nzchar(df$vlm_group_id))) {
        toupper(df$vlm_group_id[which(nzchar(df$vlm_group_id))[1]])
      } else {
        toupper(group)
      }
      
      nm <- if (nrow(df) && any(nzchar(df$short_name))) {
        as.character(df$short_name[which(nzchar(df$short_name))[1]])
      } else {
        testcd
      }
      
      # Handle missing or invalid values
      if (testcd %in% c("NA", "") || is.na(testcd)) testcd <- toupper(group)
      
      if (nm %in% c("NA", "") || is.na(nm)) {
        # Provide standard test names for common vital signs
        nm <- switch(toupper(group),
                     "WEIGHT" = "Body Weight",
                     "HEIGHT" = "Height",
                     "TEMP" = "Body Temperature",
                     "PULSE" = "Pulse Rate",
                     "SYSBP" = "Systolic Blood Pressure",
                     "DIABP" = "Diastolic Blood Pressure",
                     "RESP" = "Respiratory Rate",
                     "HR" = "Heart Rate",
                     "BMI" = "Body Mass Index",
                     testcd  # Default to TESTCD if no standard name available
        )
      }
      
      # Clean up test names - remove directional annotations
      nm <- gsub("\\s*\\((?i:horizontal|vertical|supine|standing)\\)\\s*", "", nm, perl = TRUE)
      nm <- trimws(nm)
      
      return(list(testcd = testcd, test = nm))
      
    }, error = function(e) {
      # Fallback if specification lookup fails
      warning("Failed to extract test info for group '", group, "': ", e$message)
      return(list(testcd = toupper(group), test = toupper(group)))
    })
  }
  
  codelist_for <- function(var_name, group) {
    df <- dom_spec[ toupper(dom_spec$variable_name) == toupper(var_name) &
                      (toupper(dom_spec$vlm_group_id) == toupper(group) |
                         startsWith(toupper(dom_spec$collection_group_id), toupper(group))), , drop = FALSE]
    cl <- unique(na.omit(as.character(df$codelist)))
    if (length(cl)) {
      cl[[1]]
    } else {
      var_key <- toupper(var_name)
      if (var_key == paste0(dom, "ORRESU")) "C66770"
      else if (var_key == paste0(dom, "POS")) "C71148"
      else if (var_key == paste0(dom, "LOC")) "C74456"
      else if (var_key == paste0(dom, "LAT")) "C99073"
      else if (var_key == paste0(dom, "METHOD")) "C85492"
      else ""
    }
  }
  datetime_sources <- function(group) {
    cand_date <- c(sprintf("%s_%sDAT", group, dom), sprintf("%s_VDAT", group), sprintf("%s_DATE", group), sprintf("%s_DT", group))
    cand_time <- c(sprintf("%s_%sTIM", group, dom), sprintf("%s_VTIM", group), sprintf("%s_TIME", group), sprintf("%s_TM", group))
    date_vars <- cand_date[cand_date %in% raw_cols]
    time_vars <- cand_time[cand_time %in% raw_cols]
    if (!length(date_vars) && "VISDAT" %in% raw_cols) date_vars <- "VISDAT"
    list(date = date_vars, time = time_vars)
  }
  
  # Code Generation ----
  cat("\nGenerating R code...\n")
  
  L <- character()
  
  # Generate file header with metadata
  header_line <- paste("#", paste(rep("=", 76), collapse = ""))
  L <- c(L, header_line)
  L <- c(L, sprintf("# Auto-generated SDTM %s Domain Mapping Code", dom))
  L <- c(L, header_line)
  L <- c(L, "#")
  L <- c(L, sprintf("# Generated by: CDISC 360I SDTM Oak Code Generator"))
  L <- c(L, sprintf("# Generated on: %s", format(Sys.time(), "%Y-%m-%d %H:%M:%S")))
  L <- c(L, sprintf("# Domain: %s", dom))
  L <- c(L, sprintf("# Source files:"))
  L <- c(L, sprintf("#   - Specification: %s", basename(spec_path)))
  L <- c(L, sprintf("#   - Raw data: %s", basename(raw_csv_path)))
  L <- c(L, sprintf("#   - Controlled terminology: %s", basename(ct_csv_path)))
  L <- c(L, "#")
  L <- c(L, "# Dependencies: sdtm.oak, dplyr")
  L <- c(L, header_line)
  L <- c(L, "")
  
  # Load required libraries
  L <- c(L, "# Load required libraries")
  L <- c(L, "library(sdtm.oak)")
  L <- c(L, "library(dplyr)")
  L <- c(L, "")
  
  # Data loading and preparation
  L <- c(L, "# ==============================================================================")
  L <- c(L, "# Data Loading and Preparation")
  L <- c(L, "# ==============================================================================")
  L <- c(L, "")
  L <- c(L, "# Load raw CDASH data")
  L <- c(L, sprintf("%s_raw <- read.csv('%s', stringsAsFactors = FALSE)", tolower(dom), raw_csv_path))
  L <- c(L, "")
  L <- c(L, "# Load study controlled terminology")
  L <- c(L, sprintf("study_ct <- read.csv('%s', stringsAsFactors = FALSE)", ct_csv_path))
  L <- c(L, "")
  L <- c(L, "# Generate oak ID variables for data tracking")
  subj_candidates <- c("USUBJID","SUBJID","PATNUM","PATID","SUBJECT")
  pat_var <- subj_candidates[subj_candidates %in% raw_cols][1]; if (is.na(pat_var)) pat_var <- "SUBJID"
  L <- c(L, sprintf("%s_raw <- %s_raw %%>%%", tolower(dom), tolower(dom)))
  L <- c(L, sprintf("  generate_oak_id_vars("))
  L <- c(L, sprintf("    pat_var = '%s',", pat_var))
  L <- c(L, sprintf("    raw_src = '%s'", dom))
  L <- c(L, "  )")
  L <- c(L, "")
  L <- c(L, "# Set up ID variables for sdtm.oak functions")
  L <- c(L, "id_vars <- oak_id_vars()")
  L <- c(L, "")
  
  # Generate individual parameter mappings
  L <- c(L, "# ==============================================================================")
  L <- c(L, "# Individual Parameter Mappings")
  L <- c(L, "# ==============================================================================")
  L <- c(L, "#")
  L <- c(L, "# Each parameter (TESTCD) is processed individually to create topic-specific")
  L <- c(L, "# datasets with their associated qualifiers (TEST, ORRES, ORRESU, etc.)")
  L <- c(L, "#")
  L <- c(L, "")
  
  if (length(groups) == 0) {
    cat("⚠ No parameter groups found - generating minimal structure\n")
  } else {
    cat("Generating mappings for", length(groups), "parameter groups:\n")
  }
  
  for (i in seq_along(groups)) {
    g <- groups[i]
    cat("  [", i, "/", length(groups), "] Processing", g, "...\n")
    ti <- test_info(g)
    anchor <- if (sprintf("%s_%sORRES", g, dom) %in% raw_cols) sprintf("%s_%sORRES", g, dom) else raw_cols[1]
    dt <- datetime_sources(g)
    
    # Generate parameter-specific section
    L <- c(L, sprintf("# ------------------------------------------------------------------------------"))
    L <- c(L, sprintf("# %s: %s (%s)", g, ti$test, ti$testcd))
    L <- c(L, sprintf("# ------------------------------------------------------------------------------"))
    L <- c(L, "")
    L <- c(L, sprintf("%s_%s <- ", tolower(g), tolower(dom)))
    # Map TESTCD (Test Code) using hardcode_ct
    L <- c(L, "  # Map TESTCD (Test Code)")
    L <- c(L, "  hardcode_ct(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", anchor),
           sprintf("    tgt_var = '%sTESTCD',", dom),
           sprintf("    tgt_val = '%s',", ti$testcd),
           "    ct_spec = study_ct,",
           "    ct_clst = 'C66741',",
           "    id_vars = id_vars",
           "  ) %>%")
    L <- c(L, "")
    L <- c(L, "  # Filter for records where TESTCD is not missing")
    L <- c(L, "  # Only these records need qualifier mappings")
    L <- c(L, sprintf("  dplyr::filter(!is.na(.data$%sTESTCD)) %%>%%", dom))
    L <- c(L, "")
    # Map TEST (Test Name) using hardcode_ct
    L <- c(L, "  # Map TEST (Test Name)")
    L <- c(L, "  hardcode_ct(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", anchor),
           sprintf("    tgt_var = '%sTEST',", dom),
           sprintf("    tgt_val = '%s',", ti$test),
           "    ct_spec = study_ct,",
           "    ct_clst = 'C67153',",
           "    id_vars = id_vars",
           "  ) %>%")
    L <- c(L, "")
    # Map ORRES (Original Result) using assign_no_ct
    rc <- sprintf("%s_%sORRES", g, dom)
    if (rc %in% raw_cols) {
      L <- c(L, "  # Map ORRES (Original Result)")
      L <- c(L, "  assign_no_ct(",
             sprintf("    raw_dat = %s_raw,", tolower(dom)),
             sprintf("    raw_var = '%s',", rc),
             sprintf("    tgt_var = '%sORRES',", dom),
             "    id_vars = id_vars",
             "  ) %>%")
      L <- c(L, "")
    }
    # Map qualifier variables using controlled terminology
    qualifier_vars <- c("ORRESU", "POS", "LOC", "LAT", "METHOD")
    qualifier_names <- c("Original Units", "Position", "Location", "Laterality", "Method")
    
    for (i in seq_along(qualifier_vars)) {
      vn <- qualifier_vars[i]
      vn_desc <- qualifier_names[i]
      rc <- sprintf("%s_%s%s", g, dom, vn)
      
      if (rc %in% raw_cols) {
        cl <- codelist_for(paste0(dom, vn), g)
        L <- c(L, sprintf("  # Map %s%s (%s)", dom, vn, vn_desc))
        L <- c(L, "  assign_ct(",
               sprintf("    raw_dat = %s_raw,", tolower(dom)),
               sprintf("    raw_var = '%s',", rc),
               sprintf("    tgt_var = '%s%s',", dom, vn),
               "    ct_spec = study_ct,",
               sprintf("    ct_clst = '%s',", cl),
               "    id_vars = id_vars",
               "  ) %>%")
        L <- c(L, "")
      }
    }
    # TPT/TPTNUM/STAT
    for (vn in c("TPT","TPTNUM","STAT")) {
      rc <- sprintf("%s_%s%s", g, dom, vn)
      if (rc %in% raw_cols) {
        L <- c(L, "  assign_no_ct(",
               sprintf("    raw_dat = %s_raw,", tolower(dom)),
               sprintf("    raw_var = '%s',", rc),
               sprintf("    tgt_var = '%s%s',", dom, vn),
               "    id_vars = id_vars",
               "  ) %>%")
      }
    }
    # Remove the trailing %>% from the last line if it exists
    if (length(L) > 0 && grepl("  \\) %>%$", L[length(L)])) {
      L[length(L)] <- gsub(" %>%$", "", L[length(L)])
    }
    L <- c(L, "")
  }
  if (!length(groups)) {
    warning("No parameter groups detected for domain ", dom)
  }
  # Combine all parameter datasets
  L <- c(L, "")
  L <- c(L, "# ==============================================================================")
  L <- c(L, "# Combine Individual Parameters")
  L <- c(L, "# ==============================================================================")
  L <- c(L, "#")
  L <- c(L, "# Combine all individual parameter datasets into a single findings dataset")
  L <- c(L, "#")
  L <- c(L, "")
  
  binders <- paste0(sprintf("%s_%s", tolower(groups), tolower(dom)), collapse = ", ")
  L <- c(L, sprintf("%s <- dplyr::bind_rows(%s) %%>%%", dom, binders))
  L <- c(L, "")
  
  # Map common qualifiers that apply to all parameters
  L <- c(L, "# ==============================================================================")
  L <- c(L, "# Common Qualifiers Mapping")
  L <- c(L, "# ==============================================================================")
  L <- c(L, "#")
  L <- c(L, "# Map qualifiers that are common to all parameters (date/time, visit, etc.)")
  L <- c(L, "#")
  L <- c(L, "")
  
  # Check for common date/time variables
  common_date_vars <- c("VISDAT", "VDAT", "DATE", "DT")
  common_time_vars <- c("VITIM", "VTIM", "TIME", "TM")
  date_found <- common_date_vars[common_date_vars %in% raw_cols]
  time_found <- common_time_vars[common_time_vars %in% raw_cols]
  
  # Add datetime mapping if common date/time variables exist
  if (length(date_found) || length(time_found)) {
    datetime_vars <- c(date_found, time_found)
    rv <- paste0("c(", paste0(sprintf("'%s'", datetime_vars), collapse = ", "), ")")
    L <- c(L, sprintf("  # Map %sDTC (Date/Time of Collection)", dom))
    L <- c(L, "  assign_datetime(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = %s,", rv),
           sprintf("    tgt_var = '%sDTC',", dom),
           "    raw_fmt = 'dd-mmm-yyyy'",
           "  ) %>%")
    L <- c(L, "")
  }
  
  # Map common timing point variables if they exist
  timing_vars <- c("TMPTC", "TPT", "TPTC")
  timing_found <- timing_vars[timing_vars %in% raw_cols]
  if (length(timing_found)) {
    L <- c(L, sprintf("  # Map %sTPT from %s using assign_ct", dom, timing_found[1]))
    L <- c(L, "  assign_ct(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", timing_found[1]),
           sprintf("    tgt_var = '%sTPT',", dom),
           "    ct_spec = study_ct,",
           "    ct_clst = 'TPT',",
           "    id_vars = id_vars",
           "  ) %>%")
    L <- c(L, sprintf("  # Map %sTPTNUM from %s using assign_ct", dom, timing_found[1]))
    L <- c(L, "  assign_ct(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", timing_found[1]),
           sprintf("    tgt_var = '%sTPTNUM',", dom),
           "    ct_spec = study_ct,",
           "    ct_clst = 'TPTNUM',",
           "    id_vars = id_vars",
           "  ) %>%")
  }
  
  # Map common visit variables if they exist
  visit_vars <- c("INSTANCE", "VISIT")
  visit_found <- visit_vars[visit_vars %in% raw_cols]
  if (length(visit_found)) {
    L <- c(L, sprintf("  # Map VISITNUM from %s using assign_ct", visit_found[1]))
    L <- c(L, "  assign_ct(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", visit_found[1]),
           "    tgt_var = 'VISITNUM',",
           "    ct_spec = study_ct,",
           "    ct_clst = 'VISITNUM',",
           "    id_vars = id_vars",
           "  ) %>%")
    L <- c(L, sprintf("  # Map VISIT from %s using assign_no_ct", visit_found[1]))
    L <- c(L, "  assign_no_ct(",
           sprintf("    raw_dat = %s_raw,", tolower(dom)),
           sprintf("    raw_var = '%s',", visit_found[1]),
           "    tgt_var = 'VISIT',",
           "    id_vars = id_vars",
           "  )")
  }
  
  L <- c(L, "")
  L <- c(L, "# ==============================================================================")
  L <- c(L, "# SDTM Derived Variables")
  L <- c(L, "# ==============================================================================")
  L <- c(L, "#")
  L <- c(L, "# Create derived variables required for SDTM compliance")
  L <- c(L, "# - STUDYID, DOMAIN, USUBJID: Study and subject identifiers")
  L <- c(L, "# - STRESC, STRESN, STRESU: Standardized results and units")
  L <- c(L, "# - VISITDY: Planned study day of visit")
  L <- c(L, "# - ELTM, TPTREF: Timing reference variables")
  L <- c(L, "#")
  L <- c(L, "")
  
  L <- c(L, sprintf("%s <- %s %%>%%", dom, dom))
  L <- c(L, "  dplyr::mutate(",
         sprintf("    DOMAIN = '%s',", dom),
         sprintf("    # Get STUDYID from %s_raw using oak_id matching", tolower(dom)),
         sprintf("    STUDYID = %s_raw$STUDYID[match(oak_id, %s_raw$oak_id)],", tolower(dom), tolower(dom)),
         "    # Create USUBJID by combining STUDYID and patient_number (from oak_id_vars)",
         "    USUBJID = paste0(.data$STUDYID, '-', .data$patient_number),",
         "    # Derive VSSTRESC (Character Result in Standard Format)",
         "    # For vital signs, STRESC typically standardizes terminology and units",
         sprintf("    %sSTRESC = dplyr::case_when(", dom),
         sprintf("      is.na(.data$%sORRES) | .data$%sORRES == '' ~ NA_character_,", dom, dom),
         "      # Standardize non-numeric results (e.g., 'NEGATIVE' -> 'NEGATIVE')",
         sprintf("      !grepl('^[0-9.+-]+$', .data$%sORRES) ~ toupper(trimws(.data$%sORRES)),", dom, dom),
         "      # For numeric results, keep as character but standardized",
         sprintf("      TRUE ~ as.character(.data$%sORRES)", dom),
         "    ),",
         "    # Derive VSSTRESN (Numeric Result in Standard Units)",
         sprintf("    %sSTRESN = dplyr::case_when(", dom),
         sprintf("      is.na(.data$%sORRES) | .data$%sORRES == '' ~ NA_real_,", dom, dom),
         "      # Only convert numeric values",
         sprintf("      grepl('^[0-9.+-]+$', .data$%sORRES) ~ as.numeric(.data$%sORRES),", dom, dom),
         "      # Non-numeric results get NA for STRESN",
         "      TRUE ~ NA_real_",
         "    ),",
         "    # Derive VSSTRESU (Standard Units)",
         "    # TODO: Implement unit standardization based on TESTCD",
         "    # For now, use original units - should be enhanced with unit conversion logic",
         sprintf("    %sSTRESU = dplyr::case_when(", dom),
         sprintf("      is.na(.data$%sSTRESN) ~ NA_character_,", dom),
         sprintf("      TRUE ~ .data$%sORRESU", dom),
         "    ),",
         "    # VISITDY - Planned Study Day of Visit (protocol-specific, set as placeholder)",
         "    VISITDY = NA_integer_,",
         "    # Derive timing reference variables (placeholder)",
         sprintf("    %sELTM = NA_character_,  # Elapsed Time from Time Point Reference", dom),
         sprintf("    %sTPTREF = NA_character_  # Time Point Reference", dom),
         "  ) %>%")
  L <- c(L, "")
  L <- c(L, "  # Create sequence numbers within subject")
  L <- c(L, sprintf("  dplyr::group_by(STUDYID, USUBJID) %%>%%"))
  L <- c(L, sprintf("  dplyr::mutate(%sSEQ = dplyr::row_number()) %%>%%", dom))
  L <- c(L, "  dplyr::ungroup() %>%")
  L <- c(L, "")
  # Final variable selection - keep only SDTM variables
  L <- c(L, "  # Select final SDTM variables")
  final_vars <- c("STUDYID", "DOMAIN", "USUBJID", sprintf("%sSEQ", dom), sprintf("%sTESTCD", dom),
                  sprintf("%sTEST", dom), sprintf("%sPOS", dom), sprintf("%sORRES", dom), sprintf("%sORRESU", dom),
                  sprintf("%sSTRESC", dom), sprintf("%sSTRESN", dom), sprintf("%sSTRESU", dom),
                  sprintf("%sSTAT", dom), sprintf("%sLOC", dom), "VISITNUM", "VISIT", "VISITDY",
                  sprintf("%sDTC", dom), sprintf("%sTPT", dom), sprintf("%sTPTNUM", dom),
                  sprintf("%sELTM", dom), sprintf("%sTPTREF", dom))
  final_vars_str <- paste0("'", final_vars, "'", collapse = ", ")
  L <- c(L, sprintf("  dplyr::select(dplyr::any_of(c(%s)))", final_vars_str))
  L <- c(L, "")
  L <- c(L, "")
  L <- c(L, paste("#", paste(rep("-", 48), collapse = "")))
  L <- c(L, "# Save Results")
  L <- c(L, paste("#", paste(rep("-", 48), collapse = "")))
  L <- c(L, sprintf("write.csv(%s, '%s_from_sdtm_oak_codegen.csv', row.names = FALSE)", dom, dom))
  L <- c(L, sprintf("cat('✓ SDTM %s dataset successfully created: %s_from_sdtm_oak_codegen.csv\\n')", dom, dom))
  L <- c(L, sprintf("cat('Dataset dimensions:', nrow(%s), 'rows x', ncol(%s), 'columns\\n')", dom, dom))
  
  # Write output file if specified
  if (!is.null(out_r_path)) {
    tryCatch({
      writeLines(L, out_r_path)
      cat("✓ Generated R code saved to:", out_r_path, "\n")
    }, error = function(e) {
      warning("Failed to write output file: ", e$message)
    })
  }
  
  # Final validation and summary
  cat("\n=== Code Generation Complete ===\n")
  cat("Generated code lines:", length(L), "\n")
  cat("Parameter groups processed:", length(groups), "\n")
  if (length(groups) > 0) {
    cat("Groups:", paste(groups, collapse = ", "), "\n")
  }
  cat("Timestamp:", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n")
  cat("=====================================\n\n")
  
  invisible(L)
}

emit_findings_oak_from_spec("cdisc_collection_dataset_specializations_draft.xlsx",
                            "VS.csv",
                            "study_ct.csv",
                            domain = "VS",
                            out_r_path = "VS.R")
