FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1 VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN apt-get update \
	&& apt-get install -y --no-install-recommends python3 python3-pip python3-venv python3-dev curl ca-certificates git libcairo2 libcairo2-dev libxml2-utils libcurl4-openssl-dev libxml2-dev libssl-dev wget unzip gpg software-properties-common \
	&& python3 -m venv $VIRTUAL_ENV \
	&& $VIRTUAL_ENV/bin/pip install --upgrade pip \
	&& useradd -m notebook \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

RUN set -eux; \
	apt-get update; \ 
	mkdir -p /usr/share/keyrings; \ 
	curl -fsSL https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | gpg --dearmor -o /usr/share/keyrings/cran-archive-keyring.gpg; \ 
	echo "deb [signed-by=/usr/share/keyrings/cran-archive-keyring.gpg] https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/" > /etc/apt/sources.list.d/cran-r.list; \ 
	apt-get update; \ 
	apt-get install -y --no-install-recommends r-base r-base-dev; \ 
	R --version; \ 
	rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt

RUN $VIRTUAL_ENV/bin/pip install -r /tmp/requirements.txt

WORKDIR /workspace

EXPOSE 8888




CMD ["jupyter-lab", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=", "--NotebookApp.password="]
