FROM postgres:18

ADD ./init-db.sh /docker-entrypoint-initdb.d/

RUN apt-get update && \
    apt-get install -y wget git python3 pip python3-pandas python3-sqlalchemy python3-psycopg2 && \
    rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/alidootson/UpdatedCDISCPilotData.git

WORKDIR "/UpdatedCDISCPilotData/UpdatedCDISCPilotData/CDASH/csv versions"

COPY db-import.py .

EXPOSE 5432

# The following ENTRYPOINT is commented out to allow the default Postgres entrypoint.
# Uncomment for debugging or to run an interactive shell instead.
#ENTRYPOINT [ "/bin/bash" ]



