#!/bin/bash

echo "DEBUG: POSTGRES_DB = $POSTGRES_DB"
echo "DEBUG: POSTGRES_USER = $POSTGRES_USER"
echo "DEBUG: POSTGRES_PASSWORD = $POSTGRES_PASSWORD"
echo "DEBUG: CLINOPS_DB = $CLINOPS_DB"
echo "DEBUG: CLINOPS_USER = $CLINOPS_USER"
echo "DEBUG: CLINOPS_PASSWORD = $CLINOPS_PASSWORD"
 
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $CLINOPS_USER;
    GRANT ALL PRIVILEGES ON DATABASE $CLINOPS_DB TO $CLINOPS_USER;
    ALTER DATABASE $CLINOPS_DB OWNER TO $CLINOPS_USER;
    ALTER USER $CLINOPS_USER WITH PASSWORD '$CLINOPS_PASSWORD';
EOSQL
 
